version: "3.7"
services:
  app:
    container_name: berth-reservation-admin
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn start
