version: "3.7"
services:
  app:
    container_name: berth-reservation-admin
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn start
